/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package org.mauiappjnilibsample;

import java.util.UUID;

/**
 * Generates a random string everytime it is called.
 */
public class RandomString {
    public String generate() {
        return "FromJava: " + UUID.randomUUID().toString().substring(0, 10);
    }
}
