using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Threading.Tasks;

namespace MauiAppJnilibSample.Models
{
    /// <summary>
    /// Some data that is generated by the Java service.
    /// 
    /// <para>
    /// Note that this is not used in this sample; just 
    /// kept here as a placeholder. If some data other than
    /// strings are generated by the Java service, this 
    /// data can be modelled as a class like this.
    /// </para>
    /// </summary>
    public class SomeData
    {
        public SomeData() { }
    }
}
