/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package org.mauiappjnilibsample;

import org.junit.jupiter.api.Test;
import static org.junit.jupiter.api.Assertions.*;

class RandomDataTest {
    @Test void generateReturnsNewStringEverytime() {
        RandomData classUnderTest = new RandomData();
        String s1 = classUnderTest.generate();
        String s2 = classUnderTest.generate();
        
        assertFalse(s1.equals(s2), "generate(): should return new string everytime it is called");
    }
}
